### ISSUE TITLE
Exception ignored in: <bound method PyFetion.__del__ of <__main__.PyFetion object at 0x00000000034996D8>>

### ISSUE THREAD

**Issue by perillaseed** [yijingping/pyfetion#1]
Traceback (most recent call last):
  File "pyfetion.py", line 33, in __del__
  File "pyfetion.py", line 55, in _logout
  File "pyfetion.py", line 77, in _post
  File "D:\Python34\lib\site-packages\requests\sessions.py", line 504, in post
  File "D:\Python34\lib\site-packages\requests\sessions.py", line 447, in request
  File "D:\Python34\lib\site-packages\requests\sessions.py", line 365, in prepare_request
  File "D:\Python34\lib\site-packages\requests\utils.py", line 73, in get_netrc_auth
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable

**Comment by yijingping** [comment]
请提供详细一点的信息。比如NoneType是哪个参数，下面代码中“print url, data, resp.text”打印的信息，一起其它一些日志输出

    def _post(self, url, data={}):
        if not self._session:
            self._session = requests.Session()

        resp = self._session.post(url, data=data)
        print url, data, resp.text
        return resp

**Comment by perillaseed** [comment]
It's OK now, maybe is the problem of my requests version, I just upgraded it, then everything is ok now.
